#在application.properties/或者application.yml文件中没有添加数据库配置信息.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supperpj?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 233235
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.fzt.qdms.dao

logging:
  level:
    com:
      example:
        mapper: debug
